### PR TITLE
Merge pull request #1 from ManuSetty/master

### PR DESCRIPTION
**Pull request by beruhdejene**
Hello,

I have a very limited bioinformatics background, i feel like i should put that out there. I am using the provided sample mass cytometry file to do this analysis and the PCA option is not showing up on the gui.
screen shot 2018-11-01 at 10 38 24 am

### CODE REVIEW

**Comment by ManuSetty** [comment]
Hello 

We are not actively maintaining the GUI at this point. We recommend using Jupyter notebook for the full functionality : http://nbviewer.jupyter.org/github/ManuSetty/wishbone/blob/master/notebooks/Wishbone_for_mass_cytometry.ipynb

Thanks 
Manu

**Comment by beruhdejene** [comment]
Hi Manu,

Okay, thanks. So, another issue I'm running into is getting these error messages after attempting to do wishbone analysis. 
screen shot 2018-11-01 at 5 00 06 pm

And if i just go ahead and try to visualize with marker trajectory, i get the follwing 
screen shot 2018-11-01 at 5 00 49 pm

Thank you,
Beruh

**Comment by ManuSetty** [comment]
Hello Beruh

Can you check if there are NAs in the data - this could cause the
correlations between runs to be mis calculated.

Manu

**Comment by beruhdejene** [comment]
I'm not quite sure how to do that. I opened the raw file in textedit and I see  "NAs"... One difference I saw between the sample data and my data is that the sample data is FCS3.1 and my data is FCS3.0. I noticed there are differences in the first few lines between the two formats. Could that be part of the problem?

Beruh

**Comment by awnimo** [comment]
Hi Beruh,

I will try and help you with this issue.
can you please share a sample file of FCS3.0 format? if it's too big to upload you can attach the first 1000 rows of it as a sample.

Thank you,
Awni

**Comment by beruhdejene** [comment]
Hi Awni,

Thank you. I copied the first 1000 rows from one of my data set.

[BD43sample.fcs.txt](https://github.com/ManuSetty/wishbone/files/2544039/BD43sample.fcs.txt)

**Comment by beruhdejene** [comment]
Hi Awni,

I just wanted to follow up with you regarding the sample that I have sent you. Were you able to access it and have you been able to make any progress?

Thank you,
Beruh

**Comment by beruhdejene** [comment]
Dear Manu,

I haven't heard anything in a while. I am just wondering if there is still someone who might be able to help with this issue.

Thanks,
Beruh

**Comment by ManuSetty** [comment]
Sorry for the delayed response Beruh. @awnimo is looking at this and will get back to you shortly.

**Comment by awnimo** [comment]
> Hi Awni,
> 
> Thank you. I copied the first 1000 rows from one of my data set.
> 
> [BD43sample.fcs.txt](https://github.com/ManuSetty/wishbone/files/2544039/BD43sample.fcs.txt)

Dear Beruh,

I'm sorry it took that long to respond to your inquiry.

I tried to open the attached file but the following error occurred, which I believe may relate to the fact that the file is short while its metadata were conserved as the original:

ValueError: cannot reshape array of size 76787 into shape (206254,50)

If it's not a trouble to you, please upload the full data file, and I'll take it from there.
[error_log.txt](https://github.com/ManuSetty/wishbone/files/2793487/error_log.txt)

**Comment by beruhdejene** [comment]
Hi Awni,

Here is one of my full data. Thank you in advance for your help.

Beruh 
[BD45_sample.fcs copy.zip](https://github.com/ManuSetty/wishbone/files/2797350/BD45_sample.fcs.copy.zip)

**Comment by awnimo** [comment]
It seems the file doesn't follow the correct specification for FCS files. 

To solve this I have opened your file using `flowCore` parser in R (which is probably less sensitive to encoding errors) and exporting back to FCS. You can follow these steps in R:

> install.packages("flowCore")
> if (!requireNamespace("BiocManager", quietly = TRUE))
	install.packages("BiocManager")

> x <- read.FCS( "HTKW045_Concat_normalized.fcs" , transformation = FALSE )
> write.FCS( x , "HTKW045_Concat_normalized_v1.fcs" )

The new encoded file (attached here as `_v1.fcs` was loaded into wishbone and processed without errors:

> scdata = wishbone.wb.SCData.from_fcs(fcs_file=os.path.expanduser('HTKW045_Concat_normalized_v1.fcs'))

[FCS data format - wishbone.ipynb.gz](https://github.com/ManuSetty/wishbone/files/2798014/FCS.data.format.-.wishbone.ipynb.gz)
[HTKW045_Concat_normalized_v1.fcs.gz](https://github.com/ManuSetty/wishbone/files/2798015/HTKW045_Concat_normalized_v1.fcs.gz)
[wishbone.wb.SCData.from_fcs_error_log.txt](https://github.com/ManuSetty/wishbone/files/2798017/wishbone.wb.SCData.from_fcs_error_log.txt)

**Comment by beruhdejene** [comment]
Also, 
x <- read.FCS( "HTKW045_Concat_normalized.fcs" , transformation = FALSE )
gives error.
HTKW045_Concat_normalized.fcs' is not a valid file

**Pull request closed without merging**
